UPtables/script/parser.rb, UPtables/script/timetabling.lp
erledigt: #29 @roschaefer review
=> 29 gringo4 syntax

UPtables/app/controllers/timetables_controller.rb, UPtables/app/models/room.rb, UPtables/app/models/timeframe.rb, UPtables/app/models/timetable_entry.rb, UPtables/app/models/weekday.rb, UPtables/app/views/timetables/show.html.haml, UPtables/db/migrate/20150205000256_create_rooms.rb, UPtables/db/migrate/20150205003432_change_room_in_timetable_entry.rb, UPtables/db/migrate/20150205004238_rename_room_to_room_id_in_timetable_entries.rb, UPtables/db/migrate/20150205005125_create_weekdays.rb, UPtables/db/migrate/20150205005307_create_timeframes.rb, UPtables/db/migrate/20150205010355_change_day_and_time_in_timetable_entry.rb, UPtables/db/schema.rb, UPtables/db/seeds.rb, UPtables/script/facts.lp, UPtables/script/parser.rb, UPtables/test/fixtures/rooms.yml, UPtables/test/fixtures/timeframes.yml, UPtables/test/fixtures/weekdays.yml, UPtables/test/models/room_test.rb, UPtables/test/models/timeframe_test.rb, UPtables/test/models/weekday_test.rb
erledigt #38
@felixKubicek Review bitte
=> Räume und Zeiten in der DB verlinkt

UPtables/app/views/timetables/index.html.haml, UPtables/app/views/timetables/show.html.haml, UPtables/db/migrate/20150206200039_add_costs_to_timetable.rb, UPtables/db/schema.rb, UPtables/script/parser.rb
resolves #56
@felixKubicek review bitte
=> added costs to model and view

UPtables/app/models/timetable.rb, UPtables/app/models/timetable/entry.rb, UPtables/app/views/timetables/show.html.haml, UPtables/script/parser.rb
1) fixes #40 
2) Performance thanks to ActiveRecord::Base.transaction
3) Timetable::Entry depends on Timetable
=> dependant model Timetable::Entry, SQL Transactions, Model namespaces

UPtables/config/application.rb
=> disabled scaffolding of helper_speds, routing_specs, view_specs

UPtables/app/models/room.rb, UPtables/spec/models/room_spec.rb
=> Fixed room controller nilpointer exception

UPtables/app/views/timetables/show.html.haml
resolves #51 
@carstenbyl review bitte
=> room capacity is displayed in timetable#show

UPtables/app/controllers/rooms_controller.rb, UPtables/app/models/room.rb, UPtables/features/new_rooms.feature, UPtables/features/step_definitions/steps.rb
=> 78 weekdays nil in room controller

UPtables/app/models/course.rb, UPtables/app/models/curriculum.rb, UPtables/app/models/ects_module.rb, UPtables/config/initializers/inflections.rb, UPtables/config/routes.rb, UPtables/db/migrate/20150218225930_create_ects_modules.rb, UPtables/db/migrate/20150218230423_create_courses_ects_modules_join_table.rb, UPtables/db/migrate/20150218231208_create_curricula.rb, UPtables/db/migrate/20150218231303_create_curricula_ects_modules_join_table.rb, UPtables/db/schema.rb, UPtables/spec/factories/course.rb, UPtables/spec/factories/curriculum.rb, UPtables/spec/factories/ects_module.rb, UPtables/spec/integration/job_spec.rb, UPtables/spec/matcher/be_scheduled_at_different_times.rb, UPtables/spec/models/curriculum_spec.rb, UPtables/spec/models/ects_module_spec.rb, UPtables/spec/spec_helper.rb
=> 5 eligible courses

UPtables/app/controllers/teachers_controller.rb, UPtables/app/models/teacher.rb, UPtables/app/views/rooms/index.html.haml, UPtables/app/views/teachers/_form.html.haml, UPtables/app/views/teachers/index.html.haml, UPtables/app/views/teachers/new.html.haml, UPtables/spec/models/teacher_spec.rb
resolves #34 @roschaefer review please
=> 34 add teachers

UPtables/app/models/timetable/entry.rb, UPtables/app/models/timetable/overfull_room.rb, UPtables/app/views/timetables/show.html.haml, UPtables/db/migrate/20150225204249_create_timetable_overfull_rooms.rb, UPtables/db/schema.rb, UPtables/lib/asp/job.rb, UPtables/lib/asp/model.rb, UPtables/spec/factories/timetable/entry.rb, UPtables/spec/integration/job_spec.rb
=> 84 notice overfull rooms

UPtables/lib/asp/job.rb, UPtables/lib/asp/solver.rb
=> implemented time out, not testable unfortunately

UPtables/Gemfile, UPtables/Gemfile.lock, UPtables/app/assets/javascripts/application.js, UPtables/app/assets/stylesheets/application.scss, UPtables/app/assets/stylesheets/timetables.scss, UPtables/app/views/courses/index.html.haml, UPtables/app/views/courses/show.html.haml, UPtables/app/views/layouts/application.html.haml, UPtables/app/views/rooms/_form.html.haml, UPtables/app/views/rooms/index.html.haml, UPtables/app/views/rooms/show.html.haml, UPtables/app/views/teachers/_form.html.haml, UPtables/app/views/teachers/index.html.haml, UPtables/app/views/timetables/index.html.haml, UPtables/app/views/timetables/show.html.haml
also notice the last HOTFIX on master
resolves #48
=> prettied up layout, included bootstrap rails

UPtables/app/assets/stylesheets/application.scss, UPtables/app/views/layouts/application.html.haml
=> resolved #108

UPtables/Gemfile, UPtables/Gemfile.lock, UPtables/app/assets/javascripts/application.js, UPtables/app/assets/stylesheets/application.scss, UPtables/app/views/curricula/_form.html.haml, UPtables/app/views/ects_modules/_form.html.haml
=> Multi select jquery

UPtables/app/controllers/teachers_controller.rb, UPtables/app/views/rooms/_form.html.haml, UPtables/app/views/teachers/_form.html.haml
=> proper caption for unavailabilities tables

UPtables/app/assets/javascripts/check_whole_day.js, UPtables/app/controllers/rooms_controller.rb, UPtables/app/mixins/has_unavailabilities.rb, UPtables/app/models/room.rb, UPtables/app/models/teacher.rb, UPtables/app/views/rooms/_form.html.haml, UPtables/app/views/teachers/_form.html.haml, UPtables/features/step_definitions/steps.rb, UPtables/spec/models/room_spec.rb
=> 101 select all checkbox

UPtables/app/assets/stylesheets/timetables.scss, UPtables/app/views/timetables/show.html.haml
=> 98 timetabe view fixed width height

UPtables/Gemfile, UPtables/Gemfile.lock, UPtables/app/controllers/timetables_controller.rb, UPtables/app/views/timetables/index.html.haml, UPtables/db/migrate/20150228082954_add_optimum_to_timetable.rb, UPtables/db/schema.rb, UPtables/features/asp_timeout.feature, UPtables/features/step_definitions/steps.rb, UPtables/features/support/env.rb, UPtables/lib/asp/job.rb, UPtables/lib/asp/model.rb, UPtables/lib/asp/solver.rb, UPtables/spec/integration/job_spec.rb
=> 106 107 timeout configuration

UPtables/Gemfile, UPtables/Gemfile.lock, UPtables/app/assets/javascripts/application.js, UPtables/app/controllers/courses_controller.rb, UPtables/app/models/course.rb, UPtables/app/models/recommendation.rb, UPtables/app/views/courses/_form.html.haml, UPtables/app/views/courses/_recommendation_fields.html.haml, UPtables/app/views/courses/show.html.haml, UPtables/db/migrate/20150301162521_create_recommendations.rb, UPtables/features/recommendation_for_course.feature, UPtables/features/step_definitions/steps.rb, UPtables/features/support/env.rb, UPtables/spec/factories/recommendation.rb, UPtables/spec/factories/teacher/unavailability.rb, UPtables/spec/models/recommendation_spec.rb
=> 114 recommendations

UPtables/app/views/courses/index.html.haml, UPtables/app/views/curricula/index.html.haml, UPtables/app/views/ects_modules/index.html.haml, UPtables/app/views/teachers/index.html.haml
=> bootstrap table for modules and curricula

UPtables/app/controllers/curricula_controller.rb, UPtables/app/models/curriculum.rb, UPtables/app/models/curriculum/unavailability.rb, UPtables/app/views/curricula/_form.html.haml, UPtables/app/views/curricula/show.html.haml, UPtables/app/views/rooms/show.html.haml, UPtables/db/migrate/20150304084230_create_curriculum_unavailabilities.rb, UPtables/db/schema.rb, UPtables/features/interface/curriculum_unavailabilities.feature, UPtables/features/step_definitions/steps.rb
@felixKubicek review please
fixes #86
=> 97 curriculum unavailabilites

UPtables/app/assets/javascripts/application.js, UPtables/app/assets/stylesheets/application.scss, UPtables/app/models/course.rb, UPtables/app/models/ects_module.rb, UPtables/app/views/curricula/_form.html.haml, UPtables/app/views/ects_modules/_form.html.haml
resolves #104, #103 @roschaefer review please
=> 103 sort multiselects

.gitignore, UPtables/app/models/course.rb, UPtables/app/models/curriculum.rb, UPtables/app/models/curriculum/unavailability.rb, UPtables/app/models/timetable.rb, UPtables/features/asp/curriculum_unavailabilities.feature, UPtables/features/asp/mandatory_courses.feature, UPtables/features/step_definitions/asp_steps.rb, UPtables/features/step_definitions/steps.rb, UPtables/lib/asp/configuration.rb, UPtables/lib/asp/constraint.rb, UPtables/lib/asp/constraints/basic_structure.lp, UPtables/lib/asp/constraints/soft/curriculum_unavailabilities.lp, UPtables/lib/asp/job.rb, UPtables/lib/asp/solver.rb, UPtables/spec/factories/curriculum/unavailability.rb, UPtables/spec/integration/job_spec.rb, UPtables/spec/integration/solver_spec.rb
@felixKubicek review please
fixes #85
=> 97 asp curriculum unavailabilities

UPtables/app/models/course/component.rb, UPtables/spec/models/course/component_spec.rb
=> added and tested validation of participants

UPtables/features/asp/room_sizes.feature, UPtables/features/step_definitions/asp_steps.rb
@felixKubicek I created this pull request just to close the issue with the room sizes
review plz
fixes #6
=> added cucumber test to check for the room sizes

UPtables/app/models/course/component.rb, UPtables/features/asp/double_lectures.feature, UPtables/features/step_definitions/asp_steps.rb, UPtables/lib/asp/constraint.rb, UPtables/lib/asp/constraints/hard/double_lectures.lp, UPtables/lib/asp/constraints/soft/double_lectures.lp, UPtables/spec/models/course/component_spec.rb
why do I have to change the implementation? What happened?
fixes #11
=> 11 double lectures

UPtables/features/asp/mandatory_courses_for_first_and_third_semester.feature, UPtables/features/step_definitions/asp_steps.rb, UPtables/lib/asp/constraints/hard/mandatory_and_recommended_in_same_semester.lp
=> 13 mandatory courses for first semester

UPtables/features/asp/mandatory_courses.feature, UPtables/features/asp/recommended_semester.feature, UPtables/features/step_definitions/asp_steps.rb, UPtables/lib/asp/constraint.rb, UPtables/lib/asp/constraints/soft/recommended_semester.lp, UPtables/lib/asp/constraints/soft/same_curriculum.lp
=> 32 semester recommendations

UPtables/features/asp/mandatory_courses.feature, UPtables/features/asp/mandatory_courses_for_first_and_third_semester.feature, UPtables/features/step_definitions/asp_steps.rb, UPtables/lib/asp/constraints/hard/mandatory_and_recommended_in_same_semester.lp
=> consider type of course component for mandatory hard constraints

UPtables/db/seeds.rb, UPtables/db/seeds_old.rb, UPtables/lib/asp/constraints/soft/double_lectures.lp
@felixKubicek review please (greetings from malte)
=> Presentation
